                 
                            
        -- SQL DDL autogenerated by CAM-2-model            
        -- Description: Generated for POO.vwAgreement  by XSD 2 CAM generator v2.31            
        -- Owner: To be Completed            
        -- Date: 2015-05-28T15:44:26            
        -- Version: 0.1            
        -- Script: v1.15            
        --            
        -- Database: POOdatabase            
                    
        --            
        -- Table structure for table VW_AGREEMENT            
        -- Primary Key(s): `POOdemo.VW_AGREEMENT.AGREEMENT_ID`, `POOdemo.VW_AGREEMENT.AGREEMENT_TYPE_ID`, `POOdemo.VW_AGREEMENT.AIP_ACCOUNTING_SOURCE_ROLE_ID`            
        --            
        DROP TABLE IF EXISTS `POOdatabase`.`VW_AGREEMENT`;            
        CREATE TABLE `POOdatabase`.`VW_AGREEMENT` (            
        `AGREEMENT_ID` int(6) NOT NULL ,            
        `AGREEMENT_TYPE_ID` int(6) NOT NULL ,            
        `AGREEMENT_TYPE_ABBR` varchar(8) NOT NULL ,            
        `AIP_CODE` varchar(2) DEFAULT NULL,            
        `AIP_ACCOUNTING_SOURCE_ROLE_ID` int(6) NOT NULL ,            
        `AGREEMENT_BEGIN_REINSURANCE_YEAR` int(4) NOT NULL DEFAULT '0',            
        `AGREEMENT_END_REINSURANCE_YEAR` int(4) NOT NULL DEFAULT '0',            
        `AIP_BUSINESS_NAME` varchar(55) NOT NULL DEFAULT '',            
        `STREET1_ADDRESS` varchar(65) DEFAULT NULL,            
        `STREET2_ADDRESS` varchar(35) DEFAULT NULL,            
        `CITY_NAME` varchar(35) DEFAULT NULL,            
        `STATE_ABBR` varchar(2) DEFAULT NULL,            
        `ZIP_CODE` varchar(5) DEFAULT NULL,            
        `ZIP_EXTENSION_CODE` varchar(4) DEFAULT NULL,            
        `PHONE_NUMBER` varchar(10) DEFAULT NULL,            
        `ACTIVE_AGREEMENT_FLAG` boolean NOT NULL DEFAULT '0',            
        `AGREEMENT_VALUE` decimal(6,4) NOT NULL DEFAULT '0.0',            
        `AGREEMENT_NOTES` varchar(1000) DEFAULT NULL,            
        `AGREEMENT_EXPIRY_REASON_CODE` varchar(255) DEFAULT NULL,            
        `AIP_LAST_UPDATE_DATE` date NOT NULL DEFAULT '0000-00-00',            
        `AIP_LAST_UPDATE_USER_ID` int(6) NOT NULL DEFAULT '0',            
        PRIMARY KEY (`AGREEMENT_ID`, `AGREEMENT_TYPE_ID`, `AIP_ACCOUNTING_SOURCE_ROLE_ID`)            
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1;            
        
